package com.example.backend.controller;
import com.example.backend.dto.message.MessageResponse; import com.example.backend.entity.*; import com.example.backend.exception.*; import com.example.backend.repository.*; import org.springframework.http.*; import org.springframework.messaging.simp.SimpMessagingTemplate; import org.springframework.security.core.Authentication; import org.springframework.web.bind.annotation.*; import java.util.*;
@RestController @RequestMapping("/api/v1/conversations")
public class ConversationController { private final ConversationRepository conversations; private final ConversationParticipantRepository participants; private final MessageRepository messages; private final UserRepository users; private final SimpMessagingTemplate broker;
 public ConversationController(ConversationRepository c,ConversationParticipantRepository p,MessageRepository m,UserRepository u,SimpMessagingTemplate b){conversations=c;participants=p;messages=m;users=u;broker=b;}
 @GetMapping public List<Long> list(Authentication a){User u=(User)a.getPrincipal();return participants.findByUser(u).stream().map(x->x.getConversation().getId()).toList();}
 @PostMapping public ResponseEntity<Long> create(@RequestParam Long userId,Authentication a){User me=(User)a.getPrincipal();User other=users.findById(userId).orElseThrow(()->new ResourceNotFoundException("Utilisateur introuvable")); if(me.getId().equals(other.getId()))throw new ConflictException("Conversation invalide"); Conversation c=conversations.save(new Conversation());participants.save(new ConversationParticipant(c,me));participants.save(new ConversationParticipant(c,other));return ResponseEntity.status(HttpStatus.CREATED).body(c.getId());}
 @GetMapping("/{id}/messages") public List<MessageResponse> listMessages(@PathVariable Long id,Authentication a){Conversation c=owned(id,(User)a.getPrincipal());return messages.findByConversationOrderByCreatedAtAsc(c).stream().map(MessageResponse::from).toList();}
 @PostMapping("/{id}/messages") public ResponseEntity<MessageResponse> send(@PathVariable Long id,@RequestBody Map<String,String> body,Authentication a){Conversation c=owned(id,(User)a.getPrincipal());String content=Optional.ofNullable(body.get("content")).map(String::trim).filter(x->!x.isBlank()).orElseThrow(()->new ConflictException("Message vide")); Message saved=messages.save(new Message(c,(User)a.getPrincipal(),content));MessageResponse response=MessageResponse.from(saved); participants.findAll().stream().filter(p->p.getConversation().getId().equals(id)).forEach(p->broker.convertAndSendToUser(p.getUser().getEmail(),"/queue/messages",response));return ResponseEntity.status(HttpStatus.CREATED).body(response);}
 @PutMapping("/messages/{messageId}/read") public ResponseEntity<Void> read(@PathVariable Long messageId,Authentication a){Message m=messages.findById(messageId).orElseThrow(()->new ResourceNotFoundException("Message introuvable"));owned(m.getConversation().getId(),(User)a.getPrincipal());m.markRead();messages.save(m);return ResponseEntity.noContent().build();}
 private Conversation owned(Long id,User u){Conversation c=conversations.findById(id).orElseThrow(()->new ResourceNotFoundException("Conversation introuvable"));if(!participants.existsByConversationAndUser(c,u))throw new ForbiddenException("Accès refusé");return c;}}
