package com.example.backend.controller;
import com.example.backend.dto.common.PagedResponse; import com.example.backend.dto.notification.NotificationResponse; import com.example.backend.entity.Notification; import com.example.backend.entity.User; import com.example.backend.exception.ResourceNotFoundException; import com.example.backend.repository.NotificationRepository;
import org.springframework.data.domain.PageRequest; import org.springframework.http.ResponseEntity; import org.springframework.security.core.Authentication; import org.springframework.web.bind.annotation.*; import java.time.LocalDateTime;
@RestController @RequestMapping("/api/v1/notifications")
public class NotificationController { private final NotificationRepository repository; public NotificationController(NotificationRepository repository){this.repository=repository;}
 @GetMapping public ResponseEntity<PagedResponse<NotificationResponse>> all(Authentication auth,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size){User user=(User)auth.getPrincipal();return ResponseEntity.ok(PagedResponse.from(repository.findByRecipientOrderByCreatedAtDesc(user,PageRequest.of(Math.max(0,page),Math.min(50,Math.max(1,size)))),NotificationResponse::from));}
 @GetMapping("/unread") public ResponseEntity<Long> unread(Authentication auth){return ResponseEntity.ok(repository.countByRecipientAndReadAtIsNull((User)auth.getPrincipal()));}
 @PutMapping("/{id}/read") public ResponseEntity<NotificationResponse> read(@PathVariable Long id,Authentication auth){Notification n=owned(id,(User)auth.getPrincipal());n.setReadAt(LocalDateTime.now());return ResponseEntity.ok(NotificationResponse.from(repository.save(n)));}
 @PutMapping("/read-all") public ResponseEntity<Void> readAll(Authentication auth){User u=(User)auth.getPrincipal();repository.findByRecipientOrderByCreatedAtDesc(u,PageRequest.of(0,50)).forEach(n->{if(n.getReadAt()==null)n.setReadAt(LocalDateTime.now());});return ResponseEntity.noContent().build();}
 @DeleteMapping("/{id}") public ResponseEntity<Void> delete(@PathVariable Long id,Authentication auth){repository.delete(owned(id,(User)auth.getPrincipal()));return ResponseEntity.noContent().build();}
 private Notification owned(Long id,User user){Notification n=repository.findById(id).orElseThrow(()->new ResourceNotFoundException("Notification introuvable"));if(!n.getRecipient().getId().equals(user.getId()))throw new ResourceNotFoundException("Notification introuvable");return n;}}
